### ISSUE TITLE
Master::ping Function should have a longer timeout when using Broadcast ID

### ISSUE THREAD

**Issue by LegacyMecha** [ROBOTIS-GIT/Dynamixel2Arduino#106]
When using broadcast ID, if there's no dynamixel ID within #1 or #2 IDs, the ping seems to fail (tested on 2mb baud). So if I have ID #1 and #5, it seems to works fine, but if I only have ID #5 if fails to find it. I ran same ping with a 50ms timeout and it worked. I think the default timeout should be increased correctly for broadcast ID so we don't have to manually set it when using Broadcast ID on ping.

**Comment by ROBOTIS-Will** [comment]
@LegacyMecha 
Thank you for reporting the issue.
I'll look into this!
