### ISSUE TITLE
0.1.3 tagged but 0.1.2 in library.properties

### ISSUE THREAD

**Issue by bradleyayers** [ROBOTIS-GIT/Dynamixel2Arduino#11]
Is `library.properties` supposed to be updated to say 0.1.3?

**Comment by OpusK** [comment]
@bradleyayers 

It was my mistake. ;)
I have [corrected this](https://github.com/ROBOTIS-GIT/Dynamixel2Arduino/commit/34fbb6139c38b5243a5099df49d59e50140cc5ac).
Thank you for the report.
