### ISSUE TITLE
Ping the motor every time you send a command?

### ISSUE THREAD

**Issue by chen-tianjian** [ROBOTIS-GIT/Dynamixel2Arduino#18]
Hello Kei,

Thanks for providing this library. I have a question: why do you want to ping() the motor every time you send a command? I guess pinging once in the setup to gather all model numbers and IDs is enough? I am afraid that too much communication slow things down because the computing power of Arduino is very limited. (Or, if I read your code wrong please also let me know)

Thanks so much,
Tianjian

https://github.com/ROBOTIS-GIT/Dynamixel2Arduino/blob/fa2d0270e77e48b3ee0cb835674c01f18ab30153/src/Dynamixel2Arduino.cpp#L777

**Comment by chen-tianjian** [comment]
Sorry, I found it, it will not ping repeatedly.

**Comment by OpusK** [comment]
Hi, @chen-tianjian 

I'm sorry for the late answer.
As you say, it doesn't ping repeatedly.

However, there are no comments in the code, and naming was misleading, so I'll try to organize them later when I comment on the code.

Anyway, thank you for your attention :)
Feel free to leave an issue for any comments while using.
