### ISSUE TITLE
readControlTableItem

### ISSUE THREAD

**Issue by THEb0nny** [ROBOTIS-GIT/Dynamixel2Arduino#94]
Hi, I usually example with https://emanual.robotis.com/docs/en/software/arduino_ide/ for readControlTableItem.
dxl.readControlTableItem(PRESENT_VOLTAGE, 1) but it turns out 'PRESENT_VOLTAGE' was not declared in that scope.
I would like to get the targetPosition value that the motor should get. This PRESENT_POSITION?

**Comment by THEb0nny** [comment]
I forgot to add this...
using namespace ControlTableItem;

**Comment by ROBOTIS-Will** [comment]
@THEb0nny 
Thanks for the update.
Some Arduino boards use an identical definition such as LED so we had to specify our namespace in the D2A library.
